name: Compile Lazarus Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Free Pascal (using a prebuilt image)
      run: sudo apt-get install fpc

    - name: Compile Lazarus Project
      run: fpc project1.lpr
