name: Compile Lazarus Project

on:
  push:
    branches:
      - main  # Możesz zmienić na nazwę swojej gałęzi
  pull_request:
    branches:
      - main  # Trigger, jeśli robisz pull request na gałąź 'main'

jobs:
  build:
    runs-on: windows-latest  # Używamy Windowsa, ponieważ instalujemy Free Pascal

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Pobieramy kod z repozytorium

    - name: Install Free Pascal
      run: |
        Invoke-WebRequest -Uri "https://freepascal.org/download.var" -OutFile "fpc_installer.exe"
        Start-Process -FilePath "fpc_installer.exe" -ArgumentList "/VERYSILENT" -Wait  # Instalujemy Free Pascal

    - name: Compile Lazarus Project
      run: |
        fpc project1.lpr  # Kompilowanie projektu Lazarus (tutaj zakłada się, że Twój plik to 'project1.lpr')
