name: Compile Lazarus Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Free Pascal
        run: |
          Invoke-WebRequest -Uri "https://freepascal.org/download.var" -OutFile "fpc_installer.exe"
          Start-Process -FilePath "fpc_installer.exe" -ArgumentList "/VERYSILENT" -Wait
          
      - name: Compile Lazarus project
        run: |
          fpc Project1.pas

      - name: Verify exe creation
        run: |
          if exist "Project1.exe" (
            echo "Build successful"
          ) else (
            echo "Build failed"
            exit 1
          )

      - name: Upload exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-exe
          path: Project1.exe
