name: Compile Lazarus Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Free Pascal
        run: |
          Invoke-WebRequest -Uri "https://freepascal.org/download.var" -OutFile "fpc.zip"
          Expand-Archive -Path "fpc.zip" -DestinationPath "C:\fpc"

      - name: Add Free Pascal to PATH
        run: |
          $env:PATH = "C:\fpc\bin\i386-win32;$env:PATH"
        
      - name: Compile Lazarus project
        run: |
          fpc Project1.pas

      - name: Verify exe creation
        run: |
          if exist "Project1.exe" (
            echo "Build successful"
          ) else (
            echo "Build failed"
            exit 1
          )

      - name: Upload exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-exe
          path: Project1.exe
