name: Compile Lazarus Project

on:
  push:
    branches:
      - main  # Może to być nazwa twojej gałęzi, np. 'main' lub 'master'
  pull_request:
    branches:
      - main  # Zdarzenie triggerujące, np. otwieranie PR

jobs:
  build:
    runs-on: windows-latest  # Określenie systemu operacyjnego

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Pobieranie kodu z repozytorium

    - name: Install Free Pascal
      run: |
        Invoke-WebRequest -Uri "https://freepascal.org/download.var" -OutFile "fpc_installer.exe"
        Start-Process -FilePath "fpc_installer.exe" -ArgumentList "/VERYSILENT" -Wait

    - name: Compile Lazarus Project
      run: |
        cd path_to_your_project  # Upewnij się, że ścieżka jest poprawna
        fpc your_project.lpr  # Kompilowanie pliku Lazarus
